version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti1706githubpackagesyncProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: LowerFSPackage
  version: "1.0"
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: AddIntsPackage
  gitServerName: srcCtrl_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/AddIntsPackage/_git
  gitUsername: ArtiKhare
  gitBranch: master
services:
- serviceName: project.serengeti1706githubpackagesync.integrations:packagesync
  packages:
  - name: Serengeti1706githubpackagesyncProject
    version: "1.0"
  - name: LowerFSPackage
    version: "1.0"
- serviceName: LowerFSPackage:lowerFS
  packages:
  - name: LowerFSPackage
    version: "1.0"
- serviceName: pub.string:toLower
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
